AWSTemplateFormatVersion: "2010-09-09"
Description: an example ec2 template that creates a t2.micro
Parameters:
  KeyName:
    Description: The EC2 Key Pair to allow SSH access to the instance
    Type: 'AWS::EC2::KeyPair::KeyName'
Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-76f0061f
    us-west-1:
      AMI: ami-655a0a20
    eu-west-1:
      AMI: ami-7fd4e10b
    ap-southeast-1:
      AMI: ami-72621c20
    ap-northeast-1:
      AMI: ami-8e08a38f
Resources:
  DummyEC2Server:
    Type: 'AWS::EC2::Instance'
    Properties:
      # amazon linux ami 2018.03.0
      # ImageId: "ami-0ff8a91507f77f867"
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      ImageId: !FindInMap
      - RegionMap
      - !Ref 'AWS::Region' # AWS:Region pseudo param returns the region this stack is run in
      - AMI
